### ISSUE TITLE
Downloaded SVGs lack style info?

### ISSUE THREAD

**Issue by TurnrDev** [matkoniecz/lunar_assembler#35]
This is what I get when I download and then open in a browser:
![image](https://user-images.githubusercontent.com/11667059/113322964-48319900-930d-11eb-8c78-0a74f0a907ae.png)

**Comment by matkoniecz** [comment]
Thanks for catching this regression! I see what went wrong.

**Comment by TurnrDev** [comment]
I'm glad because I had no clue and wouldn't have been much help if you needed more info aha

**Comment by matkoniecz** [comment]
If you are curious: see that supposed SVG file has div as first line and then `<svg>`.

That is because I added div with white background to show SVG with white background rather than site background to fix rendering SVGs on site.

But I failed to change what is saved to file, and it started to include spurious DIV.

To fix it properly I likely should set styling properly in CSS, and right now I make some other CSS fixes.
